
bukkit:
    passive:
        - "BAT"
        - "CAT"
        - "CHICKEN"
        - "COD"
        - "COW"
        - "DONKEY"
        - "FOX"
        - "HORSE"
        - "MUSHROOM_COW"
        - "MULE"
        - "OCELOT"
        - "PARROT"
        - "PIG"
        - "RABBIT"
        - "SALMON"
        - "SHEEP"
        - "SKELETON_HORSE"
        - "SNOWMAN"
        - "SQUID"
        - "STRIDER"
        - "TROPICAL_FISH"
        - "TURTLE"
        - "VILLAGER"
        - "WANDERING_TRADER"
        - "TRADER_LLAMA"
    neutral:
        - "BEE"
        - "CAVE_SPIDER"
        - "DOLPHIN"
        - "ENDERMAN"
        - "IRON_GOLEM"
        - "LLAMA"
        - "PANDA"
        - "PIGLIN"
        - "POLAR_BEAR"
        - "PUFFERFISH"
        - "SPIDER"
        - "WOLF"
        - "ZOMBIFIED_PIGLIN"
    hostile:
        - ""
    boss:
        - "ENDER_DRAGON"
        - "WITHER"